### ISSUE TITLE
Wrong options display shortly

### ISSUE THREAD

**Issue by diegograsso** [Collokia/taggy#20]
In the example page, in the filed labeled:
"Here, suggestions are generated dynamically. Free tagging is turned on, so you can enter tags that aren't in the suggestion list."
- I enter: "a" + enter, that selects "apple" => OK
- then "b" + enter, that selects "banana" => OK
- then "b", that displays the "NO found message" => OK
but when I delete that last "b", for a second 3 options are displayed: carrots, peanuts and lettuce and then the options disappear. That shouldn't happen as no text was entered.

**Comment by diegograsso** [comment]
This is not fixed yet. When It search for options I see the "No results found" message for a second  (or so) then options appear. Maybe this is caused by the debounce. It should show no thing or a "Searching" message.
Try this case in the same field of the comment above:
- type "a" => "No results found" appears, then it shows the real options
- delete the "a" => more options appear shortly and disappear.
- type "g" => "No results found" appears (That's OK)
- delete the "g" => more options appear shortly and disappear.

What's expected is:
- type "a" => "Searching" appears or nothing, then it shows the real options
- delete the "a" => nothing should appear.
- type "g" => "No results found" appears (That's OK)
- delete the "g" =>  nothing should appear.

**Comment by bevacqua** [comment]
Have you recompiled?

**Comment by diegograsso** [comment]
No,  I just pulled and executed the example as usual.

**Comment by bevacqua** [comment]
Try again and reopen if it persists. Just pushed the built `dist` files.

**Comment by diegograsso** [comment]
I compiled. It's working.
